name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Mock build output
        run: | 
          mkdir bin
          cp artifact/test.txt bin/test.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: bin/test.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.repository_owner == 'jckhoe-sandbox' && github.event_name != 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Check artifacts
        run: |
          cat bin/test.txt

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/jckhoe-sandbox/testificate:latest
          build-args: |
            TEST_ARG=bin/test.txt

